dsc-sookmyung/2022-Answer-SolutionChallenge

react-native/core/theme.ts
react-native/core/utils.ts
react-native/screens/LoginScreen.tsx

style: improve user input convenience

---

spring/notinote/build.gradle
spring/notinote/src/main/java/com/answer/notinote/Config/SwaggerConfig.java
spring/notinote/src/main/java/com/answer/notinote/Notice/controller/NoticeController.java
spring/notinote/src/main/java/com/answer/notinote/Notice/domain/entity/Notice.java
spring/notinote/src/main/java/com/answer/notinote/Notice/domain/repository/NoticeRepository.java
spring/notinote/src/main/java/com/answer/notinote/Notice/service/NoticeService.java

Spring Boot API Swagger를 통한 API 문서 작성 작업

feat: Notice OCR API

---

react-native/App.tsx
react-native/package.json
react-native/screens/TranslateScreen.tsx
react-native/types.ts
react-native/yarn.lock

Translate 화면 중 카메라로 촬영하는 부분 구현하였습니다.
- 카메라 전면/후면 전환
- 카메라 촬영 버튼
- 촬영된 이미지가 있는 경우
- 촬영된 이미지 보여주기
- 촬영 버튼을 다시 촬영 버튼으로 바꿔주기
- 다시 촬영 버튼을 누르면, 카메라 초기 화면으로 돌아가서 새로 촬영 받기

feat: implement camera

---

react-native/App.tsx
react-native/components/LogoutButton.tsx

HomeScreen custom navigation 구현
- 로그아웃 버튼
- alert 화면
- 로그아웃 시 다시 로그인 화면으로

Feat: implement home navigation

---

spring/notinote/build.gradle
spring/notinote/src/main/java/com/answer/notinote/Notice/controller/NoticeController.java
spring/notinote/src/main/java/com/answer/notinote/Notice/domain/entity/Notice.java
spring/notinote/src/main/java/com/answer/notinote/Notice/service/NoticeService.java

추후 User와 연결하여 사용자의 지정 언어에 따라서 번역 값 저장해야함

feat: Notice Translate API 

---

react-native/components/BottomDrawer.tsx
react-native/screens/TranslateScreen.tsx
react-native/types.ts

- 사진 촬영 후에 번역 전문 보여주기 (summary 삭제)
- 한글 원문 보기 버튼 / 저장 버튼
- 저장 누르면 제목 입력하게 하기 (modal)
- 하이라이트 표시
- 누르면 이벤트 캘린더 추가 여부를 묻는 팝업
- 누르면 폼 (modal)
- 제목 (기본값: [아이이름] 이벤트)
- 날짜 (고정)
- 아이 선택 `cid`
- 아이를 선택하면, 제목도 아이이름에 맞춰 변경
- 설명 (기본값: ‘’)

[#11] Feat: Implement modals

---

spring/notinote/build.gradle
spring/notinote/src/main/java/com/answer/notinote/Notice/controller/NoticeController.java
spring/notinote/src/main/java/com/answer/notinote/Notice/domain/entity/Notice.java
spring/notinote/src/main/java/com/answer/notinote/Notice/dto/NoticeRequestDto.java
spring/notinote/src/main/java/com/answer/notinote/Notice/service/NoticeService.java

feat: Cloud Natural Language

---

react-native/components/BottomDrawer.tsx

- 결과 저장 누르면, 결과 id와 제목과 오늘 날짜 전송 `id`, `title`, `date`
- 캘린더에 추가 누르면, 오늘 날짜 말고 이벤트의 날짜로 설정 `event.date`

[#11] update: request data

---

react-native/components/BottomDrawer.tsx
react-native/contexts/Auth.tsx
react-native/screens/HomeScreen.tsx
react-native/screens/IntroductionScreen.tsx
react-native/screens/JoinScreen.tsx
react-native/screens/SearchScreen.tsx
react-native/screens/TranslateScreen.tsx
react-native/services/authService.ts
react-native/types.ts

- `jwt_token`과 `refresh_token`은 `authData`에 설정
- `user` 관련 정보는 `userData`에 설정
- `authData`와 `userData` 모두 `useAuth()`를 이용해 사용 가능

[#1] update: set token and user data separately

---

react-native/screens/SearchResultScreen.tsx
react-native/screens/SearchScreen.tsx
react-native/types.ts

- 정해놓은 DB 구조와 일치하게 type과 변수 update

refactor: update types and variables

---

react-native/components/SearchedNotice.tsx
react-native/screens/SearchResultScreen.tsx
react-native/screens/SearchScreen.tsx
react-native/types.ts

refactor: update types

---

spring/notinote/build.gradle
spring/notinote/src/main/java/com/answer/notinote/Notice/controller/NoticeController.java
spring/notinote/src/main/java/com/answer/notinote/Notice/domain/entity/Notice.java
spring/notinote/src/main/java/com/answer/notinote/Notice/dto/ImageRequestDto.java
spring/notinote/src/main/java/com/answer/notinote/Notice/dto/NoticeOCRDto.java
spring/notinote/src/main/java/com/answer/notinote/Notice/dto/NoticeRequestDto.java
spring/notinote/src/main/java/com/answer/notinote/Notice/dto/NoticeSaveDto.java
spring/notinote/src/main/java/com/answer/notinote/Notice/dto/NoticeTitleListDto.java
spring/notinote/src/main/java/com/answer/notinote/Notice/service/NoticeService.java

refactor: Connect Notice with User

---

spring/notinote/src/main/java/com/answer/notinote/Child/domain/Child.java
spring/notinote/src/main/java/com/answer/notinote/Child/dto/ChildDto.java
spring/notinote/src/main/java/com/answer/notinote/Child/service/ChildService.java
spring/notinote/src/main/java/com/answer/notinote/Config/security/WebSecurityConfig.java
spring/notinote/src/main/java/com/answer/notinote/Event/controller/EventController.java
spring/notinote/src/main/java/com/answer/notinote/Event/domain/Event.java
spring/notinote/src/main/java/com/answer/notinote/Event/domain/repository/EventRepository.java
spring/notinote/src/main/java/com/answer/notinote/Event/dto/EventRegisterDto.java
spring/notinote/src/main/java/com/answer/notinote/Event/dto/EventResponseDto.java
spring/notinote/src/main/java/com/answer/notinote/Event/dto/urlResponseDto.java
spring/notinote/src/main/java/com/answer/notinote/Event/service/EventService.java
spring/notinote/src/main/java/com/answer/notinote/Event/service/GoogleCalendarService.java
spring/notinote/src/main/java/com/answer/notinote/Notice/domain/entity/Notice.java
spring/notinote/src/main/java/com/answer/notinote/Notice/domain/repository/NoticeRepository.java
spring/notinote/src/main/java/com/answer/notinote/Notice/service/NoticeService.java

[#31] fix: add index properties in event entity

---

react-native/components/BottomDrawer.tsx

- 캘린더에 이벤트 추가하면, 구글 캘린더에서 확인해볼 것이냐는 알람이 뜨고
- 알림의 확인 버튼을 누르면 사용자의 구글 캘린더로 이동

[#11] feat: add google calendar link

---

react-native/screens/HomeScreen.tsx

- 업데이트된 api에 맞게 구조 변경
- event가 없을 때 보여줄 화면 구현

[#3] feat: update api fetch & add empty event UI

---

react-native/components/Loading.tsx
react-native/screens/TranslateScreen.tsx

- `/notice/save` 를 `/notive/ocr` 로 잘못 설정해놓은 것 고침
- style 짜잘한 수정

feat: fix api url name

---

spring/notinote/src/main/java/com/answer/notinote/Auth/service/CustomUserDetailsService.java
spring/notinote/src/main/java/com/answer/notinote/Event/domain/Event.java
spring/notinote/src/main/java/com/answer/notinote/Event/dto/EventRequestDto.java
spring/notinote/src/main/java/com/answer/notinote/Notice/controller/NoticeController.java
spring/notinote/src/main/java/com/answer/notinote/Notice/dto/NoticeOCRDto.java
spring/notinote/src/main/java/com/answer/notinote/Notice/dto/NoticeSentenceDto.java
spring/notinote/src/main/java/com/answer/notinote/Notice/dto/NoticeTitleListDto.java
spring/notinote/src/main/java/com/answer/notinote/Notice/service/NoticeService.java

feat: extract event from notice

---

react-native/screens/HomeScreen.tsx

- `undefined is not an object` 에러 고침

[#3] fix: undefined is not an object

---

react-native/components/BottomDrawer.tsx
react-native/types.ts

[#11] fix: initial cid setting

---

spring/notinote/src/main/java/com/answer/notinote/Notice/controller/NoticeController.java
spring/notinote/src/main/java/com/answer/notinote/Notice/domain/entity/Notice.java
spring/notinote/src/main/java/com/answer/notinote/Notice/dto/NoticeRequestDto.java
spring/notinote/src/main/java/com/answer/notinote/Notice/service/NoticeService.java

저장된 notice의 내용을 아이별 검색필터를 추가하기 위해 cid를 추가하였음

[#25] feat: Add cid to Notice

---

spring/notinote/src/main/java/com/answer/notinote/Child/domain/Child.java
spring/notinote/src/main/java/com/answer/notinote/Child/dto/ChildDto.java

[#25] feat: Add profile image to Child

---

react-native/components/Home/NoEventBox.tsx
react-native/screens/HomeScreen.tsx
react-native/screens/IntroductionScreen.tsx

- i18n 추가 (sorry: 내가 과거 커밋에서 빼버림)
- map child에 key 추가
- 테스트용 코드 제거

[#3] fix: add missing parts

---

react-native/screens/HomeScreen.tsx

[#3] feat: add child profile image

---

spring/notinote/src/main/java/com/answer/notinote/Notice/controller/NoticeController.java
spring/notinote/src/main/java/com/answer/notinote/Notice/dto/NoticeEventListDto.java
spring/notinote/src/main/java/com/answer/notinote/Notice/dto/NoticeOCRDto.java
spring/notinote/src/main/java/com/answer/notinote/Notice/service/NoticeService.java

[#25] fix: Add Translated English Text to fastapi

---

spring/notinote/src/main/java/com/answer/notinote/Notice/controller/NoticeController.java
spring/notinote/src/main/java/com/answer/notinote/Notice/dto/NoticeOCRDto.java
spring/notinote/src/main/java/com/answer/notinote/Notice/service/NoticeService.java

[#25] fix: return notice title

---

react-native/components/BottomDrawer.tsx
react-native/locales/en.js
react-native/locales/ja.js
react-native/locales/km.js
react-native/locales/ko.js
react-native/locales/th.js
react-native/locales/vn.js
react-native/locales/zh.js
react-native/screens/TranslateScreen.tsx
react-native/types.ts
react-native/yarn.lock

- swipeable 한 뷰에서 가능한 한 스크롤 작동하게 함 (근데 진짜 스크롤 잘 안 먹음)
- 그래서 긴 텍스트라면 잘 안보이므로, 클립보드에 복사하기 기능을 긴 텍스트를 보기 위한 기능으로도 쓸 예정
- 클립보드에 복사하기 기능 구현
- 번역문 앞 부분이 잘리는 문제 해결

[#11] Translate Screen: implement feature and fix issue

---

react-native/components/BottomDrawer.tsx
react-native/screens/TranslateScreen.tsx

- 하단 버튼 (Retake, Save) 밑에 padding을 화면 비율에 맞게 다르게 함

[#11] style: implement responsive UI
